// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSjGFzFBsq1m_OSl8RvfZ9jlBjVJPnUw',
    appId: '1:554207348286:web:58c899b269a8abaef5736f',
    messagingSenderId: '554207348286',
    projectId: 'lab-3il',
    authDomain: 'lab-3il.firebaseapp.com',
    storageBucket: 'lab-3il.appspot.com',
    measurementId: 'G-XXC3DSE7LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0cEDvpZsv2wpJyA-Qu_2jV7anYNNCyY',
    appId: '1:554207348286:android:f3a7ee5d1e6e46d0f5736f',
    messagingSenderId: '554207348286',
    projectId: 'lab-3il',
    storageBucket: 'lab-3il.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybY8srmt1yujUeUrjIhqpHslr9VxKOW0',
    appId: '1:554207348286:ios:5c36828e31a9d705f5736f',
    messagingSenderId: '554207348286',
    projectId: 'lab-3il',
    storageBucket: 'lab-3il.appspot.com',
    iosBundleId: 'com.example.myChat',
  );
}
